### ISSUE TITLE
Cannot run containers from docker-compose.dev.yml

### ISSUE THREAD

**Issue by yessypp** [DivanteLtd/open-loyalty#157]
Hi,

I'm about to set this system up. 
When I run the containers , got `ERROR: for open_loyalty_frontend_dev  a bytes-like object is required, not 'str'`, etc.

My OS is centos 7 and I use docker.

```
# docker-compose -f docker/docker-compose.dev.yml up
Starting open_loyalty_db ...
open_loyalty_mail is up-to-date
Starting open_loyalty_frontend_dev ...
open_loyalty_elk is up-to-date

ERROR: for open_loyalty_frontend_dev  a bytes-like object is required, not 'str'

ERROR: for open_loyalty_db  a bytes-like object is required, not 'str'

ERROR: for frontend  a bytes-like object is required, not 'str'

ERROR: for db  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/f9aefea46cad286c086af4301fb170a368c969d157ddbeed1fdbe78775e9a449/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \\"read init-p: connection reset by peer\\"": unknown'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1107, in up
  File "compose/cli/main.py", line 1103, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 568, in execute_convergence_plan
  File "compose/service.py", line 510, in _execute_convergence_start
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 508, in <lambda>
  File "compose/service.py", line 620, in start_container_if_stopped
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[7376] Failed to execute script docker-compose
```

Note.
This is what I got from `docker-compose ps`
```
# docker-compose ps
      Name                     Command               State                 Ports
----------------------------------------------------------------------------------------------
open_loyalty_db     docker-entrypoint.sh postgres    Exit 1
open_loyalty_elk    /docker-entrypoint.sh elas ...   Up       0.0.0.0:9200->9200/tcp, 9300/tcp
open_loyalty_mail   MailHog                          Up       1025/tcp, 0.0.0.0:8186->8025/tcp
```

**Comment by colejarczyk** [comment]
It's not related to the application, but rather an issue in docker-compose that you use 

https://github.com/docker/compose/issues/6998

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
