### ISSUE TITLE
installation error is there any solution?

### ISSUE THREAD

**Issue by zandonline** [DivanteLtd/open-loyalty#23]
Fatal error: require(): Failed opening required 'E:\crm_\mobile app\code base\op
en-loyalty\backend\app/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR'
) in E:\crm_\mobile app\code base\open-loyalty\backend\app\autoload.php on line
13

**Comment by bizr** [comment]
Hello zandonline, I don't believe this project has Windows support, many parts of it's core, escpecially while on development, requires tools that are not available neither are tested on Windows. I advise you to use Docker or Vagrant and connect to your app through the API interface.
Spiros.

**Comment by zandonline** [comment]
I also tried docker buy i get this error
E:\crm_\mobile app\code base\open-loyalty\backend>docker-compose exec open_loyal
ty_backend bash

ERROR: No such service: open_loyalty_backend

**Comment by tjurczak** [comment]
Hi zandonline,

First of all you have to have propertly installed application (using docker). Description is in documentation (simple command "docker-compose up"). If you want to connect to some running container and call bash, you should type "docker-compose exec backend bash".

**Comment by zandonline** [comment]
i also tried docker but I get error. 

can any one share screen with me and install it?

$ docker-compose up
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 118, in perform_command
  File "compose\cli\main.py", line 926, in up
  File "compose\project.py", line 388, in up
  File "compose\project.py", line 614, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 90, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 183, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose

**Comment by colejarczyk** [comment]
Hi,

@zandonline we do not support Windows. And from the log message, I guess it's a problem related to Docker and configuration rather than Open Loyalty itself.
