### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by intpp** [DivanteLtd/open-loyalty#38]
After clone repository and running `docker-compose up` I go to http://localhost:8182 - the administration panel I got an error below:

cli:
```
open_loyalty_postgresql | ERROR:  relation "ol__settings" does not exist at character 210
open_loyalty_postgresql | STATEMENT:  SELECT t0.id AS id_1, t0.setting_key AS setting_key_2, t0.dtype, t0.json_value AS json_value_3, t0.string_value AS string_value_4, t0.integer_value AS integer_value_5, t0.boolean_value AS boolean_value_6 FROM ol__settings t0 WHERE t0.setting_key = $1 AND t0.dtype IN ('settingsentry', 'jsonsettingentry', 'stringsettingentry', 'integersettingentry', 'booleansettingentry') LIMIT 1
```

browser:
```
GET http://localhost:8181/app_dev.php/api/translations 500 (Internal Server Error)

{
  "error": {
    "code": 500,
    "message": "Internal Server Error",
    "exception": [
      {
        "message": "An exception occurred while executing 'SELECT t0.id AS id_1, t0.setting_key AS setting_key_2, t0.dtype, t0.json_value AS json_value_3, t0.string_value AS string_value_4, t0.integer_value AS integer_value_5, t0.boolean_value AS boolean_value_6 FROM ol__settings t0 WHERE t0.setting_key = ? AND t0.dtype IN ('settingsentry', 'jsonsettingentry', 'stringsettingentry', 'integersettingentry', 'booleansettingentry') LIMIT 1' with params [\"defaultFrontendTranslations\"]:\n\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"ol__settings\" does not exist\nLINE 1: ...value_5, t0.boolean_value AS boolean_value_6 FROM ol__settin...\n                                                             ^",
        "class": "Doctrine\\DBAL\\Exception\\TableNotFoundException",
        "trace": [
          {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "\/var\/www\/ol\/backend\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractPostgreSQLDriver.php",
            "line": 75,
            "args": [
              
            ]
          },
...
}
```

**Comment by bizr** [comment]
You didn't even bother reading the documentation before opening this issue?
Do this:
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
docker-compose exec backend phing setup
docker-compose exec backend phing demo
`
Now that the demo data and settings are in, you can use
`docker-compose up`

**Comment by jioannoucrm** [comment]
Tried this approach and we got the following errors when running "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up"

ERROR: for frontend  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/5ba3dac3fcae69b00236852bf68def631f0fddc6312013d263d5bd0ee94c05b7/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/local/lib/python3.6/site-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint open_loyalty_frontend_dev (8a99c03e9e57712e951ab4870f2f55ba05b4        b659beaec5925163a1624ea237bf): Bind for 0.0.0.0:8081 failed: port is already allocated'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 1103, in up
    cli=native_builder,
  File "/usr/local/lib/python3.6/site-packages/compose/project.py", line 570, in up
    get_deps,
  File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/local/lib/python3.6/site-packages/compose/project.py", line 556, in do
    renew_anonymous_volumes=renew_anonymous_volumes,
  File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 546, in execute_convergence_plan
    scale, detached, start
  File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 467, in _execute_convergence_create
    "Creating"
  File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 465, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 457, in create_and_start
    self.start_container(container)
  File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
