### ISSUE TITLE
failed phing command

### ISSUE THREAD

**Issue by dolphinsd** [DivanteLtd/open-loyalty#65]
Running in ubuntu command line with php5 and latest phing I get this error on setup

vlad@VLAD-PC:/mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend$ php phing-latest.phar setup
Buildfile: /mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/build.xml
PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in phar:///mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/phing-latest.phar/classes/phing/parser/ExpatParser.php:81
Stack trace:
#0 phar:///mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/phing-latest.phar/classes/phing/parser/ProjectConfigurator.php(216): ExpatParser->__construct(Object(BufferedReader))
#1 phar:///mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/phing-latest.phar/classes/phing/parser/ProjectConfigurator.php(196): ProjectConfigurator->_parse(Object(PhingXMLContext))
#2 phar:///mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/phing-latest.phar/classes/phing/parser/ProjectConfigurator.php(74): ProjectConfigurator->parse()
#3 phar:///mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/phing-latest.phar/classes/phing/Phing.php(696): ProjectConfigurator::configureProject(Object(Project), Object(PhingFile))
#4 phar:///mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/phing-latest.phar/classes/phing/Phing.php(200): Phing->runBuild()
#5 phar:/// in phar:///mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/phing-latest.phar/classes/phing/parser/ExpatParser.php on line 81

**Comment by dolphinsd** [comment]
issue can be resolved with install of this package
sudo apt-get install php-xml-parser
