### ISSUE TITLE
Composer Update Throws Error

### ISSUE THREAD

**Issue by arfeen** [DivanteLtd/open-loyalty#80]
When 'composer update' is run, it throws following error after taking parameters input:

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "fos_rest.serializer" has a dependency on a non-existent service "jms_serializer.serialization_context_factory". in /var/nginx/html/ol/backend/vendor/divante-ltd/open-loyalty-framework/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:58
Stack trace:
#0 /var/nginx/html/ol/backend/vendor/divante-ltd/open-loyalty-framework/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
#1 /var/nginx/html/ol/backend/vendor/divante-ltd/open-loyalty-framework/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(36): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehavior in /var/nginx/html/ol/backend/vendor/divante-ltd/open-loyalty-framework/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 58
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "fos_rest.seri
  alizer" has a dependency on a non-existent service "jms_serializer.serialization_context_factory". in /var/nginx/html/ol/b
  ackend/vendor/divante-ltd/open-loyalty-framework/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler
  /CheckExceptionOnInvalidReferenceBehaviorPass.php:58
  Stack trace:
  #0 /var/nginx/html/ol/backend/vendor/divante-ltd/open-loyalty-framework/vendor/symfony/symfony/src/Symfony/Component/Depen
  dencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42): Symfony\Component\DependencyInjection\Compil
  er\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
  #1 /var/nginx/html/ol/backend/vendor/divante-ltd/open-loyalty-framework/vendor/symfony/symfony/src/Symfony/Component/Depen
  dencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(36): Symfony\Component\DependencyInjection\Compil
  er\CheckExceptionOnInvalidReferenceBehavior in /var/nginx/html/ol/backend/vendor/divante-ltd/open-loyalty-framework/vendor
  /symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on li
  ne 58


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

```

**Comment by colejarczyk** [comment]
@arfeen why do you need to use composer update instead of composer install? 

When you run composer update, then composer updates all libraries to newest version according to the composer.json file. You should use always composer install which installs exactly version of libraries from composer.lock. We didn't test Open Loyalty against newest version of dependencies.
